# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - echo ""
    silent: true
  generate:
    cmds:
      - rm -rf go/grpcPassit
      - protoc --go_out=./go --go-grpc_out=./go ./proto/*.proto
      - cd go/grpcPassit && go mod init && go mod tidy